version: '3'
services:
  redis:
    image: redis:latest
    network_mode: "bridge"
    volumes:
      - "./conf/redis/data:/data"
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    restart: always
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: 'test'
      MYSQL_PASS: '123456'
      MYSQL_DATABASE: 12306
      TZ: Asia/Shanghai
    volumes:
      - "./conf/mysql/db:/var/lib/mysql"
      - "./conf/mysql/my.cnf:/etc/my.cnf"
      - "./conf/mysql/init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"

